version: '3.1'
services:
  php:
    image: swing-localdev:php7.4
    container_name: php
    entrypoint:
      - php
    command: "-v"
    working_dir: "/var/www"
    volumes:
      - .:/var/www
      
  composer:
    image: swing-localdev:php7.4
    container_name: composer
    entrypoint:
      - composer
    command: "-V"
    working_dir: "/var/www"
    volumes:
      - .:/var/www

  server:
    image: swing-localdev:php7.4
    container_name: server
    entrypoint:
      - php
    command: "-S 0.0.0.0:8580 -t /var/www/public"
    working_dir: "/var/www"
    volumes:
      - ./:/var/www
    ports:
      - 8800:8580


  npm:
    image: nodejspy
    container_name: npm
    entrypoint:
      - npm
    command: "run"
    working_dir: "/var/www"
    volumes:
      - ./:/var/www
